name: Bug report
description: Create a bug report for Stardust Labs projects. General support questions should be redirected to our [Discord](https://www.discord.gg/stardustlabs).
labels: [bug]
body:
  - type: dropdown
    id: mc
    attributes:
      label: What Minecraft version(s) does this apply to?
      multiple: true
      options:
        - 1.18.2
        - 1.19.x
        - 1.19.4
        - 1.20
    validations:
      required: true
  - type: input
    id: pack
    attributes:
      label: Project version
      description: What version of the project are you using?
      placeholder: ex. v2.3.7b
    validations:
      required: true
  - type: dropdown
    id: format
    attributes:
      label: Mod or datapack version?
      options:
        - Datapack
        - Mod (Fabric)
        - Mod (Forge)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false