name: Bug report
description: Create a bug report for Stardust Labs projects
title: "[Bug]"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        This is for bug reports only. General support questions should be redirected to our [Discord](https://www.discord.gg/stardustlabs).

        **Note**: Is your bug about the superflat or other world types? Please read [this](<https://github.com/Stardust-Labs-MC/Terralith/issues/113>) before making an issue.
  - type: dropdown
    id: mc
    attributes:
      label: What Minecraft version(s) does this apply to?
      multiple: true
      options:
        - 1.18.2
        - 1.19 - 1.19.3
        - 1.19.4
        - 1.20 - 1.20.1
        - 1.20.2
        - 1.20.3 - 1.20.4
        - 1.20.5 - 1.20.6
        - 1.21 - 1.21.1
    validations:
      required: true
  - type: input
    id: pack
    attributes:
      label: Project version
      description: What version of the project are you using?
      placeholder: ex. v2.3.7b
    validations:
      required: true
  - type: dropdown
    id: format
    attributes:
      label: Mod or datapack version?
      options:
        - Datapack
        - Fabric/Quilt Mod
        - Neoforge/Forge Mod
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
