blank_issues_enabled: true
contact_links:
  - name: Discord
    about: Get support, ask questions, and hang out on our Discord Server.
    url: https://discord.gg/stardustlabs
  - name: Wiki
    about: Useful wiki for all Stardust Labs projects.
    url: https://stardustlabs.miraheze.org/