name: Enhancement
description: Suggest an enhancement or improvement for an existing Stardust Labs project. Comlex or bigger features should be brought up in the [Discord](https://www.discord.gg/stardustlabs).
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Describe your enhancement/improvement, with context and reasoning.
      description: Ex. "Some of the Terralith Skyland biomes should [...] because [...]"
    validations:
      required: true