name: Enhancement
description: Suggest an enhancement or improvement for an existing Stardust Labs project.
title: "[Enhancement]"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        This is for minor enhancements/improvements only. Complex or bigger features should be brought up in the [Discord](https://www.discord.gg/stardustlabs).
  - type: textarea
    attributes:
      label: Describe your enhancement/improvement, with context and reasoning.
      description: Ex. "Some of the Terralith Skyland biomes should [...] because [...]"
    validations:
      required: true